#!/bin/bash
# Generate the Linux kernel debug-mmrs.c file based on Blackfin proc XML files

set -e

output="debug-mmrs.c"

cd "$(dirname "${0}")"

cat << EOF > ${output}
/* DO NOT EDIT THIS FILE
 * Automatically generated by toolchain/trunk/proc-defs/sh/create-debug-mmrs.sh
 * DO NOT EDIT THIS FILE
 */

#include <linux/debugfs.h>
#include <linux/fs.h>
#include <linux/kernel.h>
#include <linux/module.h>
#include <asm/blackfin.h>

/* Some MMRs are stupid and have different read/write addresses.
 * So let's account for that here by interjecting ourselves into
 * the normal debugfs process.
 */
struct bfin_rw_ptr_pair {
	void *read, *write;
};
static void bfin_rw_u16_set(void *data, u64 val)
{
	*(u16 *) ((struct bfin_rw_ptr_pair *)data)->write = val;
}
static u64 bfin_rw_u16_get(void *data)
{
	return *(u16 *) ((struct bfin_rw_ptr_pair *)data)->read;
}
DEFINE_SIMPLE_ATTRIBUTE(bfin_rw_u16_fops, bfin_rw_u16_get, bfin_rw_u16_set, "%llx\n");
static __init
struct dentry *debugfs_create_rw_u16(const char *name, mode_t mode,
                                     struct dentry *parent, u16 *rvalue,
                                     u16 *wvalue)
{
	struct dentry *ret;
	struct bfin_rw_ptr_pair *pair = kmalloc(sizeof(*pair), GFP_KERNEL);
	pair->read = rvalue;
	pair->write = wvalue;
	ret = debugfs_create_file(name, mode, parent, rvalue, &bfin_rw_u16_fops);
	if (ret)
		ret->d_inode->i_private = pair;
	return ret;
}

static int __init bfin_init_mmr_debugfs(void)
{
	struct dentry *top, *parent;

	printk(KERN_DEBUG "Setting up Blackfin MMR debugfs\n");

	top = debugfs_create_dir("blackfin", NULL);
	if (top == NULL)
		return -1;
EOF

for f in ../xml/ADSP-BF*-proc.xml ; do
	unset parent

	echo "Processing ${f}"

	procnum=${f}
	procnum=${procnum#*/ADSP-}
	procnum=${procnum%-proc.xml}

	# dont bother outputting code for procs we dont support
	#if ! grep -qs "^config ${procnum}" ../Kconfig ; then
	#	echo "   ... skipping ${procnum}"
	#	continue
	#fi

cat << EOF >> ${output}

#ifdef __ADSP${procnum}__
# define USE_${procnum} 1
#else
# define USE_${procnum} 0
#endif
	if (USE_${procnum}) {
EOF

	xsltproc ../xsl/debug-mmrs.xsl ${f} | LC_ALL="C" sort -u | \
	while read line ; do
		IFS=";"
		set -- ${line}
		unset IFS
		group=$1 mmr_name=$2 mmr_read=$3 mmr_write=$4 bits=$5

		if [[ -z ${mmr_name} || -z ${bits} || -z ${mmr_read} ]] ; then
			[[ ${group} == "Core" ]] && continue
			echo "Broken line generated! -> $@"
		fi

		if [[ ${parent} != "${group}" ]] ; then
cat << EOF >> ${output}

		parent = debugfs_create_dir("${group}", top);
EOF
			parent=${group}
		fi

		if [[ ${mmr_read} == ${mmr_write} ]] ; then
cat << EOF >> ${output}
		debugfs_create_x${bits}("${mmr_name}", 0600, parent, (u${bits}*)${mmr_read});
EOF
		else
cat << EOF >> ${output}
		debugfs_create_rw_x${bits}("${mmr_name}", 0600, parent, (u${bits}*)${mmr_read}, (u${bits}*)${mmr_write});
EOF
		fi
	done

cat << EOF >> ${output}

	}	/* ${procnum} */
EOF
done

cat << EOF >> ${output}

	return 0;
}

late_initcall(bfin_init_mmr_debugfs);
EOF
