#! /bin/sh
echo "This cleans, configures and builds gcc for bfin target"
DEST_DIR=/home2/raja/bfin-elf/output
DIR_TARGET_SOURCES=/home2/raja/bfin-elf/
echo "It builds and installs in $DEST_DIR"
echo "First clean ..."
make clean
make distclean
echo "Now configure ..."
./configure --host=i686-pc-linux-gnu --prefix=$DEST_DIR --exec-prefix=$DEST_DIR --target=bfin-elf --with-libbfd=$DIR_TARGET_SOURCES/binutils/bfd/libbfd.a --with-libiberty=$DEST_DIR/lib/libiberty.a --with-bfd-include-dir=$DIR_TARGET_SOURCES/binutils/bfd --with-binutils-include-dir=$DIR_TARGET_SOURCES/binutils/include --enable-languages=c
echo "Now build ..."
make -k 2>&1 | tee log.make.bfin
echo "Now install ..."
make install
