#! /bin/sh
echo "This cleans, configures and builds gcc for bfin target"
DEST_DIR=/home2/raja/bfin-elf/output1
echo "It builds and installs in $DEST_DIR"
echo "First clean ..."
make clean
make distclean
echo "Now configure ..."
./configure --host=i686-pc-linux-gnu --prefix=$DEST_DIR --exec-prefix=$DEST_DIR --target=bfin-elf --enable-languages=c
echo "Now build ..."
make -k -j4 2>&1 | tee log.make.bfin
echo "Now install ..."
#make install
