# Board definition fragment for testing via QEMU

# Load the generic configuration for this board. This will define a basic set
# of routines needed by the tool to communicate with the board.
load_generic_config "sim"

# basic-sim.exp is a basic description for the standard Cygnus simulator.
load_base_board_description "basic-sim"

set_board_info sim qemu-bfin

# "bfin" is the name of the sim subdir.
setup_sim bfin

# No linker script needed.
set_board_info ldscript "";
