# Board definition fragment for testing a FLAT toolchain

# Common Blackfin format settings
load_generic_config "bfin-fmt"

# -s80000 is for gcc.dg/dg.exp/trampoline-1.c
# if you change this value, also change gcc,stack_size below
set_board_info ldflags "-Wl,-elf2flt=-s80000";
set_board_info use_binfmt_flat 1

# Advertise slightly less than we actually have (see above) since a few
# testcases really push the limit.
set_board_info gcc,stack_size 75000
