
#define STDC_HEADERS 1
#define HAVE_SGTTY_H 1
#define HAVE_TERMIO_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_SYS_REG_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_PROCFS_H 1
#define HAVE_THREAD_DB_H 1
#define HAVE_LINUX_ELF_H 1
#define HAVE_STDLIB_H 1
#define HAVE_UNISTD_H 1
