#! /bin/sh
echo "This cleans, configures and builds gcc for bfin target"

DEST_DIR=/home2/raja/out_gdb

make clean
make distclean

#export bash_cv_have_mbstate_t=yes
export CC=bfin-elf-gcc
export KERNEL_SOURCE=/home2/sri/uClinux-dist/linux-2.6.x/


#./configure --host=i686-pc-linux-gnu --prefix=$DEST_DIR --exec-prefix=$DEST_DIR --target=bfin-elf --enable-languages=c

#./configure --build=i686-pc-linux-gnu --host=bfin-elf --prefix=$DEST_DIR --exec-prefix=$DEST_DIR --target=bfin-elf --enable-languages=c  --with-lib=/usr/bfin/today/533/lib/ 2>&1 | tee log.config.bfin

#../../configure --build=i686-pc-linux-gnu --host=bfin-elf --prefix=$DEST_DIR --exec-prefix=$DEST_DIR --target=bfin-elf --enable-languages=c 2>&1 | tee log.config.bfin

#./configure --prefix=$DEST_DIR --exec-prefix=$DEST_DIR --target=bfin-elf --enable-languages=c 2>&1 | tee log.config.bfin

./configure --prefix=$DEST_DIR --exec-prefix=$DEST_DIR --build=i686-pc-linux-gnu --host=bfin-elf --target=bfin-elf --enable-languages=c 2>&1 | tee log.config.bfin

make  2>&1 | tee log.make.bfin
#make CC=bfin-elf-gcc 2>&1 | tee log.make.bfin

make install
