/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 228
#define YY_END_OF_BUFFER 229
static yyconst short int yy_accept[520] =
    {   0,
        0,    0,    0,    0,  229,  227,  225,  225,  211,  223,
      210,  209,  191,  192,  207,  205,  202,  201,  194,  222,
      222,  193,  212,  190,  186,  227,  223,  144,  223,  223,
      223,  223,  223,  223,  223,  223,  223,   69,  223,  223,
      223,   53,   19,   18,  223,   12,   10,    8,    7,  180,
      179,  178,  223,  176,  174,  223,  223,  223,  223,  223,
      223,  208,  206,  204,  203,    0,  200,  195,    0,    0,
        0,  222,  224,    0,  222,  224,  189,  187,  213,  185,
      184,  173,  170,  223,  223,  223,  146,  147,  223,  223,
      145,    0,  143,  223,  136,  223,  223,  132,  223,  121,

      223,  119,  223,  223,  223,  223,  223,  223,  223,   99,
       98,   97,   96,   95,  223,  223,   93,  223,   91,   90,
       89,   87,  223,   81,  223,  223,   73,   82,  223,   70,
       68,  223,  223,  223,  223,   64,  223,  223,  223,   58,
      223,   55,  223,   52,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,   25,  223,  223,  223,
      223,  223,   15,   14,  223,  223,  154,  223,  177,  223,
      175,  214,  223,  223,   91,  223,  223,  223,  196,  198,
      197,  199,    0,    0,  222,  222,  222,  222,  188,  182,
      183,  223,  223,  166,  148,  149,  223,  223,  157,  158,

      223,  150,  152,  222,  223,  223,  223,  223,  223,  223,
      120,  223,  223,  115,  223,  223,  223,  223,  223,  223,
      223,  223,   94,  223,  223,  223,  223,  223,  223,   76,
       79,   74,   77,  223,  223,   75,   78,  223,   66,   65,
      223,   62,   61,  223,  223,  223,  223,  223,  223,  223,
      223,  223,   44,   39,   38,   37,   36,   35,   34,  223,
       32,   31,  223,  223,  223,  223,  223,  223,  223,   21,
      223,  223,   16,   13,  223,    9,  223,  223,  223,  223,
      223,  223,  223,  226,  181,  165,  163,  172,  171,  164,
      162,  169,  168,  223,  223,  223,  151,  153,  142,  223,

      223,  223,  223,  135,  134,  223,  123,  223,  223,  114,
      223,  223,  223,  223,  107,  106,  223,  223,  223,  223,
      223,  223,  101,  100,  223,   92,  223,   88,   85,   80,
      223,  223,   67,   63,  223,   60,   59,   57,   56,   54,
       45,  223,   50,   47,   49,   46,   48,  223,  223,   43,
       42,  223,  223,  223,  223,  223,   27,   24,   23,  223,
      223,  223,  223,  223,  223,  218,  223,  217,  223,  223,
      223,  223,  155,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  118,  223,  113,  112,  223,  223,  223,
      223,  223,  223,  223,  104,  223,  223,  223,  223,  223,

      223,  223,    2,   51,   41,   40,   33,  223,  223,  223,
       30,  223,   22,  223,  223,  223,  167,  221,  223,  223,
      223,  223,  223,  159,  156,  141,  140,  139,  138,  137,
      223,  223,  223,  223,  122,  117,  223,  223,  223,  223,
      223,  223,  223,  103,  223,  223,  223,   84,   83,   86,
       72,   71,   29,  223,  223,  223,   20,  223,  223,  223,
      219,  223,  216,  160,  161,  223,  223,  223,  223,  223,
      223,  116,  223,  110,  109,  223,  223,  223,    5,  102,
      223,  223,   28,  223,  223,   17,   11,  223,  223,  223,
      223,  131,  129,  130,  128,  125,  223,  111,  223,    6,

      105,  223,    3,    1,   26,  220,  215,  133,  126,  127,
      223,  223,  223,  124,  223,    4,  223,  108,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    6,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,    1,    1,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,    1,   59,   60,   61,    1,   62,   63,   34,   35,

       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       64,   47,   48,   65,   50,   66,   52,   53,   54,   55,
       56,   57,    1,   67,    1,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    5,    4,    5,    5,    5,    4,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        3,    5,    4,    3,    3,    3,    1,    1
    } ;

static yyconst short int yy_base[526] =
    {   0,
        0,    0,   32,   33,  766,  767,  767,  767,  767,    0,
      767,  735,  767,  767,  734,   59,  767,   60,  752,  111,
       44,  767,  767,   53,   74,  731,  158,  217,   59,  105,
       42,   95,   52,  103,  132,  709,  266,  145,   48,  109,
      316,  365,  413,  144,  710,   56,  739,    0,    0,  767,
      767,  728,  694,   57,  767,  150,   64,  716,   46,   72,
        0,  767,  767,  767,  767,  144,  767,  767,  158,  744,
      206,  221,  270,  463,  301,  767,  724,  767,  767,  767,
       89,  738,  737,  701,  122,  710,    0,    0,  209,  142,
        0,    0,  734,  122,    0,  712,  132,  128,  704,    0,

      706,    0,  689,  710,  705,  695,   63,  689,  294,  725,
        0,    0,    0,    0,  138,  703,  723,  694,    0,    0,
      686,    0,  691,  719,  181,  192,    0,    0,  177,  200,
      718,  677,  686,  187,  202,    0,  213,  694,  154,  714,
      694,    0,  682,  711,  685,  199,  689,  203,  304,  206,
      235,  215,  299,  212,  683,  684,  706,  664,  679,  668,
      667,  664,    0,    0,  668,  247,    0,  695,  767,  136,
      767,  767,  661,  669,  668,  665,  265,  666,  767,  767,
      767,  767,  697,  203,  349,  400,    0,    0,  767,  767,
      677,  303,  337,    0,    0,    0,  668,  665,    0,    0,

      244,  654,  653,    0,  264,  362,  649,  290,  665,  657,
        0,  654,  655,  368,  216,  249,  303,  328,  347,  331,
      349,  265,    0,  350,  266,  661,  677,  648,  313,    0,
        0,    0,    0,  339,  654,    0,    0,  365,    0,    0,
      646,    0,    0,  657,  641,  656,  394,  647,  385,  405,
      638,  421,  416,    0,    0,    0,    0,    0,    0,  642,
        0,    0,  391,  636,  393,  648,  639,  400,  638,    0,
      648,  411,    0,    0,  620,    0,  615,  629,  642,  625,
      634,  638,  634,  662,  767,    0,    0,    0,    0,    0,
        0,    0,    0,  627,  634,  427,    0,    0,    0,  627,

      617,  632,  452,    0,  617,  457,  651,  631,  628,  431,
      619,  460,  612,  618,    0,    0,  462,  605,  607,  440,
      623,  469,    0,    0,  458,    0,  596,    0,  641,    0,
      603,  617,    0,    0,  617,    0,    0,    0,    0,    0,
        0,  616,    0,    0,    0,    0,    0,  632,  633,    0,
        0,  614,  614,  454,  611,  461,  475,    0,    0,  612,
      608,  594,  599,  576,  602,  579,  589,    0,  602,  592,
      492,  462,    0,  465,  581,  467,  592,  468,  595,  586,
      483,  587,  576,    0,  580,    0,    0,  582,  585,  587,
      588,  573,  590,  573,    0,  581,  587,  586,  467,  486,

      572,  484,    0,    0,    0,    0,    0,  579,  505,  567,
        0,  576,    0,  577,  578,  507,    0,  573,  573,  489,
      569,  587,  588,    0,    0,    0,    0,    0,    0,    0,
      568,  524,  573,  559,    0,  586,  561,  495,  496,  558,
      545,  543,  548,    0,  497,  517,  547,    0,    0,    0,
        0,    0,    0,  500,  545,  502,    0,  505,  523,  531,
        0,  538,    0,    0,    0,  528,  418,  510,  517,  431,
      520,    0,  417,    0,    0,  431,  418,  507,    0,    0,
      394,  355,    0,  508,  345,    0,    0,  324,  304,  509,
      533,    0,    0,    0,    0,    0,  281,    0,  259,    0,

        0,  220,    0,    0,    0,    0,    0,    0,    0,    0,
      214,  178,  159,    0,   78,    0,  519,    0,  767,  583,
      588,   88,  593,  595,  597
    } ;

static yyconst short int yy_def[526] =
    {   0,
      519,    1,    1,    1,  519,  519,  519,  519,  519,  520,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  521,
      522,  519,  519,  519,  519,  519,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  519,
      519,  519,   27,  519,  519,  520,   35,   37,   41,  520,
      520,  519,  519,  519,  519,  519,  519,  519,  519,  523,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  524,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  519,  520,
      519,  519,  520,  520,  520,  520,  520,  520,  519,  519,
      519,  519,  523,  523,  519,  519,   74,  525,  519,  519,
      519,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  524,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  523,  519,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,

      520,  520,  520,  520,  520,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  520,  520,  520,  520,    0,  519,
      519,  519,  519,  519,  519
    } ;

static yyconst short int yy_nxt[836] =
    {   0,
        6,    7,    8,    9,    6,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   10,   19,   20,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   10,   37,   38,   39,   40,   41,   10,   42,   43,
       44,   45,   46,   47,   48,   10,   49,   50,   51,   52,
       10,   53,   28,   40,   42,   44,   54,   55,   56,   56,
       64,   57,   57,   67,   58,   58,   76,   79,   59,   59,
       76,   77,   78,   60,   60,  108,  171,  112,   65,   68,
       99,   75,  100,  135,  177,  166,  109,  136,  174,   92,

      175,  101,  113,   80,  102,  167,   76,   92,  103,   92,
      177,  135,  216,   92,  104,  217,  178,  113,  190,  191,
       99,  165,  102,  172,  517,   66,   69,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,  105,  195,  196,
      106,  110,  114,   73,  107,  115,  111,   73,  117,  117,
      117,  117,  137,  138,   92,  179,  116,  180,  202,  203,
      139,  131,  131,  131,  131,   74,  118,  105,  119,  181,
      120,  182,  206,   73,   82,   83,  132,  208,  209,  161,
      162,  121,  163,  122,  133,  194,  164,  206,  223,  134,
       84,   85,  173,  209,  516,  208,  110,  230,  231,  277,

       86,  111,   87,  223,  246,   88,  132,   89,  232,  233,
       90,  515,  234,  184,   91,  235,  236,  237,  284,  246,
       84,   92,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  241,   93,   93,   93,   93,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  198,  242,  252,
      241,  199,  243,  254,  260,  514,   94,  200,  244,  201,
      262,  313,  265,   95,  252,   96,  261,  243,  254,  513,
      260,   97,   98,  200,  201,  296,  244,  265,  262,  313,
      314,   96,  124,  124,  124,  124,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  261,  275,  125,  126,

      282,  127,  299,  323,  326,  296,  299,  324,  326,  249,
      314,  128,  275,  512,  511,  129,  130,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,  219,  125,  128,
      263,  130,  140,  140,  140,  140,  140,  140,  305,  255,
      220,  286,  507,  256,  221,  287,  264,  141,  257,  142,
      315,  330,  316,  258,  305,  330,  288,  289,  259,  221,
      263,  317,  321,  318,  143,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  290,  506,  141,  319,  291,
      143,  144,  144,  144,  144,  144,  144,  144,  144,  331,
      292,  293,  321,  320,  505,  300,  145,  322,  325,  310,

      146,  311,  503,  333,  331,  301,  312,  333,  319,  147,
      148,  302,  303,  322,  325,  149,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  145,  303,  148,  310,
      149,  150,  338,  348,  349,  340,  338,  341,  358,  353,
      491,  355,  359,  341,  151,  502,  152,  341,  153,  154,
      340,  155,  156,  500,  350,  353,  343,  355,  351,  157,
      344,  362,  158,  159,  492,  345,  499,  341,  160,  386,
      346,  498,  496,  387,  151,  347,  362,  373,  159,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  377,
      395,  389,  373,  392,  188,  188,  188,  188,  188,  188,

      397,  378,  380,  381,  409,  395,  398,  412,  382,  422,
      423,  411,  425,  426,  433,  447,  424,  428,  430,  409,
      380,  389,  398,  392,  188,  188,  411,  425,  448,  426,
      397,  447,  428,  430,  452,  449,  454,  412,  459,  462,
      450,  467,  468,  469,  433,  474,  475,  480,  481,  452,
      483,  497,  485,  493,  462,  486,  494,  501,  504,  508,
      474,  475,  480,  495,  490,  483,  454,  485,  459,  518,
      486,  489,  501,  504,  508,  488,  509,  487,  481,  510,
      484,  497,  482,  479,  518,   61,   61,   61,   71,  478,
       71,   71,   71,  183,  477,  183,  183,  183,  204,  204,

      188,  188,  476,  473,  472,  471,  470,  466,  465,  464,
      463,  461,  460,  458,  457,  456,  455,  453,  451,  446,
      445,  444,  443,  442,  441,  440,  439,  438,  437,  436,
      435,  434,  432,  431,  429,  427,  421,  420,  419,  399,
      418,  417,  416,  415,  414,  413,  410,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  396,  394,  393,
      391,  390,  388,  385,  384,  383,  379,  376,  375,  374,
      372,  371,  184,  370,  369,  368,  367,  366,  365,  364,
      363,  361,  360,  357,  356,  354,  352,  342,  339,  337,
      336,  335,  334,  332,  329,  328,  327,  309,  308,  307,

      306,  304,  298,  297,  295,  294,  285,  184,  283,  281,
      280,  279,  278,  276,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  253,  251,  250,  249,  248,  247,  245,
      240,  239,  238,  229,  228,  227,  226,  225,  224,  222,
      218,  215,  214,  213,  212,  211,  210,  207,  205,  197,
      194,  193,  192,  189,  184,  176,  170,  169,  168,  165,
      123,   81,   70,   63,   62,  519,    5,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519
    } ;

static yyconst short int yy_chk[836] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
       16,    3,    4,   18,    3,    4,   21,   25,    3,    4,
       21,   24,   24,    3,    4,   31,   54,   33,   16,   18,
       29,  522,   29,   39,   59,   46,   31,   39,   57,   32,

       57,   29,   33,   25,   29,   46,   21,   34,   29,   30,
       59,   39,  107,   40,   29,  107,   60,   33,   81,   81,
       29,   60,   29,   54,  515,   16,   18,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   30,   85,   85,
       30,   32,   34,   20,   30,   34,   32,   20,   35,   35,
       35,   35,   40,   40,   56,   66,   34,   66,   90,   90,
       40,   38,   38,   38,   38,   20,   35,   30,   35,   69,
       35,   69,   94,   20,   27,   27,   38,   97,   98,   44,
       44,   35,   44,   35,   38,  170,   44,   94,  115,   38,
       27,   27,   56,   98,  513,   97,   56,  125,  125,  170,

       27,   56,   27,  115,  139,   27,   38,   27,  126,  126,
       27,  512,  129,  184,   27,  129,  130,  130,  184,  139,
       27,   28,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,  134,   28,   28,   28,   28,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   89,  135,  146,
      134,   89,  135,  148,  150,  511,   28,   89,  137,   89,
      152,  215,  154,   28,  146,   28,  151,  135,  148,  502,
      150,   28,   28,   89,   89,  201,  137,  154,  152,  215,
      216,   28,   37,   37,   37,   37,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,  151,  166,   37,   37,

      177,   37,  205,  222,  225,  201,  205,  222,  225,  177,
      216,   37,  166,  499,  497,   37,   37,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,  109,   37,   37,
      153,   37,   41,   41,   41,   41,   41,   41,  208,  149,
      109,  192,  489,  149,  109,  192,  153,   41,  149,   41,
      217,  229,  217,  149,  208,  229,  192,  192,  149,  109,
      153,  218,  220,  218,   41,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  185,  193,  488,   41,  219,  193,
       41,   42,   42,   42,   42,   42,   42,   42,   42,  234,
      193,  193,  220,  219,  485,  206,   42,  221,  224,  214,

       42,  214,  482,  238,  234,  206,  214,  238,  219,   42,
       42,  206,  206,  221,  224,   42,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,   42,  206,   42,  214,
       42,   43,  247,  253,  253,  249,  247,  250,  268,  263,
      467,  265,  268,  250,   43,  481,   43,  250,   43,   43,
      249,   43,   43,  477,  253,  263,  252,  265,  253,   43,
      252,  272,   43,   43,  467,  252,  476,  250,   43,  310,
      252,  473,  470,  310,   43,  252,  272,  296,   43,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,  303,
      320,  312,  296,  317,   74,   74,   74,   74,   74,   74,

      322,  303,  306,  306,  354,  320,  325,  357,  306,  371,
      371,  356,  372,  374,  381,  399,  371,  376,  378,  354,
      306,  312,  325,  317,   74,   74,  356,  372,  400,  374,
      322,  399,  376,  378,  402,  400,  409,  357,  416,  420,
      400,  432,  432,  432,  381,  438,  439,  445,  446,  402,
      454,  471,  456,  468,  420,  458,  468,  478,  484,  490,
      438,  439,  445,  469,  466,  454,  409,  456,  416,  517,
      458,  462,  478,  484,  490,  460,  491,  459,  446,  491,
      455,  471,  447,  443,  517,  520,  520,  520,  521,  442,
      521,  521,  521,  523,  441,  523,  523,  523,  524,  524,

      525,  525,  440,  437,  436,  434,  433,  431,  423,  422,
      421,  419,  418,  415,  414,  412,  410,  408,  401,  398,
      397,  396,  394,  393,  392,  391,  390,  389,  388,  385,
      383,  382,  380,  379,  377,  375,  370,  369,  367,  366,
      365,  364,  363,  362,  361,  360,  355,  353,  352,  349,
      348,  342,  335,  332,  331,  329,  327,  321,  319,  318,
      314,  313,  311,  309,  308,  307,  305,  302,  301,  300,
      295,  294,  284,  283,  282,  281,  280,  279,  278,  277,
      275,  271,  269,  267,  266,  264,  260,  251,  248,  246,
      245,  244,  241,  235,  228,  227,  226,  213,  212,  210,

      209,  207,  203,  202,  198,  197,  191,  183,  178,  176,
      175,  174,  173,  168,  165,  162,  161,  160,  159,  158,
      157,  156,  155,  147,  145,  144,  143,  141,  140,  138,
      133,  132,  131,  124,  123,  121,  118,  117,  116,  110,
      108,  106,  105,  104,  103,  101,   99,   96,   93,   86,
       84,   83,   82,   77,   70,   58,   53,   52,   47,   45,
       36,   26,   19,   15,   12,    5,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,

      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  519,  519,  519,  519
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
#define INITIAL 0
/*
 *
 *   Copyright (c) 2003 Analog Devices Inc., 
 *
 *   04/2004 Martin Strubel <hackfin@section5.ch>
 *       Added macros for pre-classifying registers for improved
 *       parsing through bfin-parse.y.
 *       Also changed all token matches to lowercase for better readability,
 *       sacrificing the previous total upper/lowercase freedom.
 *   09/2004 Pradip Shah <pcs@rrap-software.com>
 *       prefetch, unlink and other such keywords were not usable as
 *       parameters to call. Added a start state KEYWORD which will be
 *       the default start state, achieved by calling set_start_state()
 *       before every line is parsed. When call is processed, we set
 *       the state back to INITIAL, so keywords will not be matched.
 *       Will only work for keywords that are the "command" type keywords
 *       Only PREFETCH, LINK and UNLINK currently added
 *       Only CALL & JUMP resets the state.
 *
 */
#line 23 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"

#include <stdlib.h>
#include <string.h>
#include "bfin-defs.h"
#include "bfin-parse.tab.h"
#include "as.h"

static long parse_int (char **end);
static int parse_halfreg(Register *r, int cl, char *hr);
static int parse_reg(Register *r, int type, char *rt);

// <strubi> some useful macros:
// see bfin-defs.h
// types: T_REG_R, T_REG_P, T_REG_A, T_REG_I, T_REG_B, T_REG_M

#define _REG yylval.reg


/* Define Start States ... Actually we will use exclusion.
   If no start state is specified it should match any state
   and <INITIAL> would match some keyword rules only with
   initial
*/
#define KEYWORD 1

#line 767 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 50 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"

#line 920 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 520 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 767 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_sftreset;  return REG;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_omode;     return REG;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_idle_req;  return REG;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_hwerrcause; return REG;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_excause;   return REG;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_emucause;  return REG;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return Z;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return X;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_W32; return MMOD;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return W;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return VIT_MAX;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return V; /* special: V is a statflag and a modifier */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_USP; return REG;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return TL;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return TH;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_TFU; return MMOD;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return TESTSET;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_T; return MMOD;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return S;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_SYSCFG; return REG;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return STI;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SSYNC;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_SP; return HALF_REG;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_SP | F_REG_HIGH; return HALF_REG;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_SP; return REG;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SIGNBITS;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 77 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SIGN;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 78 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_SEQSTAT; return REG;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 79 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SEARCH;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 80 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SHIFT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 81 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SCO;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SAA;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_S2RND; return MMOD;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RTX;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RTS;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 87 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RTN;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 88 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RTI;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RTE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ROT;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 91 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RND20;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 92 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RND12;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 93 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RNDL;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RNDH;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RND;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_halfreg(&yylval.reg, T_REG_R, yytext);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 99 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_RETS; return REG;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 100 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_RETI; return REG;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_RETX; return REG;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 102 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_RETN; return REG;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 103 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_RETE; return REG;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 104 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RAISE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 106 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_reg(&yylval.reg, T_REG_R, yytext);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 108 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return R;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 109 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return PRNT;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 110 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return PC;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 111 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return PACK;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 113 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_halfreg(&yylval.reg, T_REG_P, yytext);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 114 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_reg(&yylval.reg, T_REG_P, yytext);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return OUTC;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 117 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ONES;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return NOT;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 120 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return NOP;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return MNOP;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 122 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return NS;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 125 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return MIN;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 126 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return MAX;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 128 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_halfreg(&yylval.reg, T_REG_M, yytext);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 129 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_reg(&yylval.reg, T_REG_M, yytext);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 131 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return M;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 132 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LT;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 133 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LSHIFT;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 134 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LSETUP;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 136 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 137 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_LC0; return REG;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 138 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_LT0; return REG;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 139 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_LB0; return REG;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 140 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_LC1; return REG;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 141 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_LT1; return REG;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 142 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_LB1; return REG;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 144 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_halfreg(&yylval.reg, T_REG_L, yytext);
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 145 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_reg(&yylval.reg, T_REG_L, yytext);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 146 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LO;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 147 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ BEGIN 0; return JUMP_DOT_S;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 148 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ BEGIN 0; return JUMP_DOT_L;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 149 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ BEGIN 0; return JUMP;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 150 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ BEGIN 0; return JUMP_DOT_L; /* TODO: fix */}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 151 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_IU;   return MMOD;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 152 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_ISS2; return MMOD;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 153 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_IS;   return MMOD;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 154 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_IH;   return MMOD;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 155 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return IF;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 156 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_halfreg(&yylval.reg, T_REG_I, yytext);
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 157 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_reg(&yylval.reg, T_REG_I, yytext);
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 158 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return HLT;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 159 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return HI;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 160 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return GT;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 161 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return GE;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 162 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
yylval.value = M_FU; return MMOD;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 163 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_FP; return REG;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 164 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_FP; return HALF_REG;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 165 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_FP | F_REG_HIGH; return HALF_REG;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 167 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return EXTRACT;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 168 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return EXPADJ;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 169 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return EXCPT;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 170 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return EMUEXCPT;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 171 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DIVS;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 172 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DIVQ;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 173 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DISALGNEXCPT;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 174 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DEPOSIT;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 175 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DBGHALT;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 176 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DBGCMPLX;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 177 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DBGAL;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 178 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DBGAH;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 179 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DBGA;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 180 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DBG;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 181 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ _REG.regno = REG_CYCLES2; return REG; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 182 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ _REG.regno = REG_CYCLES; return REG; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 183 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return CSYNC;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 184 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return CO;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 185 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return CLI;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 187 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_CC; return CCREG;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 188 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ BEGIN 0; return CALL;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 189 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ BEGIN 0; return CALL;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 190 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BYTEUNPACK;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 191 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BYTEPACK;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 192 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BYTEOP16M;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 193 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BYTEOP16P;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 194 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BYTEOP3P;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 195 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BYTEOP2M;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 196 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BYTEOP2P;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 197 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BYTEOP1P;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 198 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BY;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 199 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BXORSHIFT;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 200 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BXOR;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 202 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BREV;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 203 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BP;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 204 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BITTST;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 205 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BITTGL;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 206 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BITSET;
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 207 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BITMUX;
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 208 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BITCLR;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 209 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_halfreg(&yylval.reg, T_REG_B, yytext);
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 210 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return parse_reg(&yylval.reg, T_REG_B, yytext);
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 211 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return B;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 212 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AZ;   return MODIFIED_STATUS_REG;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 213 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AN;   return MODIFIED_STATUS_REG;
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 214 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AQ;   return MODIFIED_STATUS_REG;
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 215 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AC0;  return MODIFIED_STATUS_REG;
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 216 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AC1;  return MODIFIED_STATUS_REG;
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 217 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AV0;  return MODIFIED_STATUS_REG;
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 218 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AV0S; return MODIFIED_STATUS_REG;
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 219 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AV1;  return MODIFIED_STATUS_REG;
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 220 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_AV1S; return MODIFIED_STATUS_REG;
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 221 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = S_VS;   return MODIFIED_STATUS_REG;
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 224 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_ASTAT; return REG;
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 225 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ASHIFT;
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 226 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ASL;
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 227 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ASR;
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 228 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ALIGN8;
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 229 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ALIGN16;
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 230 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ALIGN24;
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 231 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return A_ONE_DOT_L;
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 232 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return A_ZERO_DOT_L;
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 233 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return A_ONE_DOT_H;
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 234 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return A_ZERO_DOT_H;
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 235 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ABS;
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 236 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ABORT;
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 237 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_A1x; return REG;
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 238 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_A1w; return REG;
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 239 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_A1;  return REG_A11;
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 240 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_A0x; return REG;
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 241 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_A0w; return REG;
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 242 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
_REG.regno = REG_A0;  return REG_A00;
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 245 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return TILDA;
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 246 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _BAR_ASSIGN;
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 247 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BAR;
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 248 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _CARET_ASSIGN;
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 249 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return CARET;
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 250 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RBRACK;
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 251 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LBRACK;
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 252 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _GREATER_GREATER_GREATER_THAN_ASSIGN;
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 253 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _GREATER_GREATER_ASSIGN;
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 254 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _GREATER_GREATER_GREATER;
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 255 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return GREATER_GREATER;
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 256 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _ASSIGN_ASSIGN;
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 257 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return ASSIGN;
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 258 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _LESS_THAN_ASSIGN;
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 259 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _LESS_LESS_ASSIGN;
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 260 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LESS_LESS;
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 261 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LESS_THAN;
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 262 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LPAREN;
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 263 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return RPAREN;
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 264 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return COLON;
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 265 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SLASH;
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 266 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _MINUS_ASSIGN;
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 267 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _PLUS_BAR_PLUS;
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 268 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _MINUS_BAR_PLUS;
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 269 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _PLUS_BAR_MINUS;
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 270 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _MINUS_BAR_MINUS;
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 271 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _MINUS_MINUS;
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 272 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return MINUS;
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 273 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return COMMA;
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 274 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _PLUS_ASSIGN;
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 275 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _PLUS_PLUS;
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 276 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return PLUS;
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 277 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _STAR_ASSIGN;
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 278 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return STAR;
	YY_BREAK
case 208:
YY_RULE_SETUP
#line 279 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _AMPERSAND_ASSIGN;
	YY_BREAK
case 209:
YY_RULE_SETUP
#line 280 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return AMPERSAND;
	YY_BREAK
case 210:
YY_RULE_SETUP
#line 281 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return PERCENT;
	YY_BREAK
case 211:
YY_RULE_SETUP
#line 282 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return BANG;
	YY_BREAK
case 212:
YY_RULE_SETUP
#line 283 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return SEMICOLON;
	YY_BREAK
case 213:
YY_RULE_SETUP
#line 284 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return _ASSIGN_BANG;
	YY_BREAK
case 214:
YY_RULE_SETUP
#line 285 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return DOUBLE_BAR;
	YY_BREAK
case 215:
YY_RULE_SETUP
#line 286 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return PREFETCH;
	YY_BREAK
case 216:
YY_RULE_SETUP
#line 287 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return UNLINK;
	YY_BREAK
case 217:
YY_RULE_SETUP
#line 288 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return LINK;
	YY_BREAK
case 218:
YY_RULE_SETUP
#line 289 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return IDLE;
	YY_BREAK
case 219:
YY_RULE_SETUP
#line 290 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return IFLUSH;
	YY_BREAK
case 220:
YY_RULE_SETUP
#line 291 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return FLUSHINV;
	YY_BREAK
case 221:
YY_RULE_SETUP
#line 292 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return FLUSH;
	YY_BREAK
case 222:
YY_RULE_SETUP
#line 293 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{
         yylval.value = parse_int (&yytext);
         return NUMBER;
     }
	YY_BREAK
case 223:
YY_RULE_SETUP
#line 297 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{ 
		yylval.symbol = symbol_find_or_make(yytext);
		symbol_mark_used(yylval.symbol);
		return SYMBOL; 
		}
	YY_BREAK
case 224:
YY_RULE_SETUP
#line 302 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
{
		char *name;
		char *ref = strdup (yytext);
		if (ref[1] == 'b' || ref[1] == 'B')
		{
			name = fb_label_name((int)(ref[0]-'0'),0);
			yylval.symbol = symbol_find (name);

			if ((yylval.symbol != NULL) && (S_IS_DEFINED (yylval.symbol)))
			/* local labels are never absolute. don't waste time
					   checking absoluteness. */
			   return SYMBOL;
			as_bad ("backw. ref to unknown label \"%d:\", 0 assumed.",
						  (int)(ref[0]-'0')); 
		}
		else if (ref[1] == 'f' || ref[1] == 'F')
		{
			/*
			* forward reference. expect symbol to be undefined or
			* unknown. undefined: seen it before. unknown: never seen
			* it before.
			* construct a local label name, then an undefined symbol.
			* don't create a xseg frag for it: caller may do that.
			* just return it as never seen before.
			*/
			name = fb_label_name((int)(ref[0]-'0'),1);
			yylval.symbol = symbol_find_or_make (name);
			/* we have no need to check symbol properties. */
			return SYMBOL;
		}                                  
	}                                  
	YY_BREAK
case 225:
YY_RULE_SETUP
#line 333 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
;
	YY_BREAK
case 226:
YY_RULE_SETUP
#line 334 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
;
	YY_BREAK
case 227:
YY_RULE_SETUP
#line 335 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
return yytext[0];
	YY_BREAK
case 228:
YY_RULE_SETUP
#line 336 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"
ECHO;
	YY_BREAK
#line 2180 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(KEYWORD):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 520 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 520 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 519);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 336 "/home2/raja/testDEL/binutils/gas/./config/bfin-lex.l"

static long parse_int (char **end)
{
  char fmt = '\0';
  int not_done = 1;
  int shiftvalue = 0;
  char * char_bag;
  long value = 0;
  char c;
  char *arg = *end;

  while (*arg && *arg == ' ') arg++;

  switch (*arg) {
    case '1':    case '2':    case '3':    case '4':
    case '5':    case '6':    case '7':    case '8':    case '9':
      fmt = 'd';
      break;

    case '0':  /* Accept different formated integers hex octal and binary. */
      {
	c = *++arg; arg++;
	if (c == 'x' || c == 'X') /* hex input */
	  fmt = 'h';
	else if (c == 'b' || c == 'B')
	  fmt = 'b';
	else if (c == '.')
	  fmt = 'f';
	else {             /* octal */
	  arg--;
	  fmt = 'o';
	}
	break;
      }

    case 'd':    case 'D':    case 'h':    case 'H':
    case 'o':    case 'O':    case 'b':    case 'B':
    case 'f':    case 'F':
      {
	fmt = *arg++;
	if (*arg == '#')
	  arg++;
      }
  }

  switch (fmt) {
  case 'h':  case 'H':
    shiftvalue = 4;
    char_bag = "0123456789ABCDEFabcdef";
    break;

  case 'o':  case 'O':
    shiftvalue = 3;
    char_bag = "01234567";
    break;

  case 'b':  case 'B':
    shiftvalue = 1;
    char_bag = "01";
    break;

/*
The assembler allows for fractional constants to be created
by either the 0.xxxx or the f#xxxx format 

i.e.   0.5 would result in 0x4000

note .5 would result in the identifier .5.

The assembler converts to fractional format 1.15
by the simple rule.


value = (short)(finput*(1<<15))
*/
  case 'f':  case 'F':
  {
    float fval = 0.0;
    float pos = 10.0;
    while (1) {
      int c;
      c = *arg++;

      if (c >= '0' && c <= '9') {
        float digit = (c - '0') / pos;
        fval = fval + digit;
        pos = pos * 10.0;
      }
      else
      {
	*--arg = c;
        value = (short) (fval * (1 << 15));
        break;
      }
    }
    *end = arg+1;
    return value;
  }

  case 'd':  case 'D':
  default:
  {
    while (1) {
      int c;
      c = *arg++;
      if (c >= '0' && c <= '9')
        value = (value * 10) + (c - '0');
      else
      {
/* Constants that are suffixed with k|K are multiplied by 1024
   This suffix is only allowed on decimal constants. */
        if (c == 'k' || c == 'K')
          value *= 1024;
        else
          *--arg = c;
        break;
      }
    }
    *end = arg+1;
    return value;
  }
  }

  while (not_done) {
    char c;
    c = *arg++;
    if (c == 0 || !index (char_bag, c)) {
      not_done = 0;
      *--arg = c;
    }
    else
    {
      if (c >= 'a' && c <= 'z')
        c = c - ('a' - '9') + 1;
      else if (c >= 'A' && c <= 'Z')
        c = c - ('A' - '9') + 1;

      c -= '0';

      value = (value << shiftvalue) + c;
    }
  }
  *end = arg+1;
  return value;
}


static int parse_reg(Register *r, int cl, char *rt)
{
	// compose regno:
	r->regno = cl | (rt[1] - '0');
	return REG;
}

// Xn.Y

static int parse_halfreg(Register *r, int cl, char *rt)
{
	r->regno = cl | (rt[1] - '0');

	switch (rt[3]) {
		case 'b':
		case 'B':
			return BYTE_REG;
		case 'l':
		case 'L':
			break;
		case 'h':
		case 'H':
			r->regno |= F_REG_HIGH;
			break;
	}

	return HALF_REG;
}

/* Our start state is KEYWORD as we have command keywords such as
   PREFETCH.
*/
void 
set_start_state(void)
{
	BEGIN KEYWORD;
}



#ifndef yywrap
int
yywrap ()
{ 
    return 1;
}
#endif

