/* Auto generated:
   $ echo '#include <errno.h>' | \
     bfin-uclinux-gcc -E -dD -P - | \
     sed -r -n '/#define E.* [0-9]/{\
         s:^.* (E.*) (.*):#ifdef TARGET_\1\n# define TARGET_LINUX_\1 \2\n  [TARGET_\1] = TARGET_LINUX_\1,\n#endif:;\
         p;}'
 */
const unsigned errno_sim_to_linux_map[] = {
#ifdef TARGET_EPERM
# define TARGET_LINUX_EPERM 1
  [TARGET_EPERM] = TARGET_LINUX_EPERM,
#endif
#ifdef TARGET_ENOENT
# define TARGET_LINUX_ENOENT 2
  [TARGET_ENOENT] = TARGET_LINUX_ENOENT,
#endif
#ifdef TARGET_ESRCH
# define TARGET_LINUX_ESRCH 3
  [TARGET_ESRCH] = TARGET_LINUX_ESRCH,
#endif
#ifdef TARGET_EINTR
# define TARGET_LINUX_EINTR 4
  [TARGET_EINTR] = TARGET_LINUX_EINTR,
#endif
#ifdef TARGET_EIO
# define TARGET_LINUX_EIO 5
  [TARGET_EIO] = TARGET_LINUX_EIO,
#endif
#ifdef TARGET_ENXIO
# define TARGET_LINUX_ENXIO 6
  [TARGET_ENXIO] = TARGET_LINUX_ENXIO,
#endif
#ifdef TARGET_E2BIG
# define TARGET_LINUX_E2BIG 7
  [TARGET_E2BIG] = TARGET_LINUX_E2BIG,
#endif
#ifdef TARGET_ENOEXEC
# define TARGET_LINUX_ENOEXEC 8
  [TARGET_ENOEXEC] = TARGET_LINUX_ENOEXEC,
#endif
#ifdef TARGET_EBADF
# define TARGET_LINUX_EBADF 9
  [TARGET_EBADF] = TARGET_LINUX_EBADF,
#endif
#ifdef TARGET_ECHILD
# define TARGET_LINUX_ECHILD 10
  [TARGET_ECHILD] = TARGET_LINUX_ECHILD,
#endif
#ifdef TARGET_EAGAIN
# define TARGET_LINUX_EAGAIN 11
  [TARGET_EAGAIN] = TARGET_LINUX_EAGAIN,
#endif
#ifdef TARGET_ENOMEM
# define TARGET_LINUX_ENOMEM 12
  [TARGET_ENOMEM] = TARGET_LINUX_ENOMEM,
#endif
#ifdef TARGET_EACCES
# define TARGET_LINUX_EACCES 13
  [TARGET_EACCES] = TARGET_LINUX_EACCES,
#endif
#ifdef TARGET_EFAULT
# define TARGET_LINUX_EFAULT 14
  [TARGET_EFAULT] = TARGET_LINUX_EFAULT,
#endif
#ifdef TARGET_ENOTBLK
# define TARGET_LINUX_ENOTBLK 15
  [TARGET_ENOTBLK] = TARGET_LINUX_ENOTBLK,
#endif
#ifdef TARGET_EBUSY
# define TARGET_LINUX_EBUSY 16
  [TARGET_EBUSY] = TARGET_LINUX_EBUSY,
#endif
#ifdef TARGET_EEXIST
# define TARGET_LINUX_EEXIST 17
  [TARGET_EEXIST] = TARGET_LINUX_EEXIST,
#endif
#ifdef TARGET_EXDEV
# define TARGET_LINUX_EXDEV 18
  [TARGET_EXDEV] = TARGET_LINUX_EXDEV,
#endif
#ifdef TARGET_ENODEV
# define TARGET_LINUX_ENODEV 19
  [TARGET_ENODEV] = TARGET_LINUX_ENODEV,
#endif
#ifdef TARGET_ENOTDIR
# define TARGET_LINUX_ENOTDIR 20
  [TARGET_ENOTDIR] = TARGET_LINUX_ENOTDIR,
#endif
#ifdef TARGET_EISDIR
# define TARGET_LINUX_EISDIR 21
  [TARGET_EISDIR] = TARGET_LINUX_EISDIR,
#endif
#ifdef TARGET_EINVAL
# define TARGET_LINUX_EINVAL 22
  [TARGET_EINVAL] = TARGET_LINUX_EINVAL,
#endif
#ifdef TARGET_ENFILE
# define TARGET_LINUX_ENFILE 23
  [TARGET_ENFILE] = TARGET_LINUX_ENFILE,
#endif
#ifdef TARGET_EMFILE
# define TARGET_LINUX_EMFILE 24
  [TARGET_EMFILE] = TARGET_LINUX_EMFILE,
#endif
#ifdef TARGET_ENOTTY
# define TARGET_LINUX_ENOTTY 25
  [TARGET_ENOTTY] = TARGET_LINUX_ENOTTY,
#endif
#ifdef TARGET_ETXTBSY
# define TARGET_LINUX_ETXTBSY 26
  [TARGET_ETXTBSY] = TARGET_LINUX_ETXTBSY,
#endif
#ifdef TARGET_EFBIG
# define TARGET_LINUX_EFBIG 27
  [TARGET_EFBIG] = TARGET_LINUX_EFBIG,
#endif
#ifdef TARGET_ENOSPC
# define TARGET_LINUX_ENOSPC 28
  [TARGET_ENOSPC] = TARGET_LINUX_ENOSPC,
#endif
#ifdef TARGET_ESPIPE
# define TARGET_LINUX_ESPIPE 29
  [TARGET_ESPIPE] = TARGET_LINUX_ESPIPE,
#endif
#ifdef TARGET_EROFS
# define TARGET_LINUX_EROFS 30
  [TARGET_EROFS] = TARGET_LINUX_EROFS,
#endif
#ifdef TARGET_EMLINK
# define TARGET_LINUX_EMLINK 31
  [TARGET_EMLINK] = TARGET_LINUX_EMLINK,
#endif
#ifdef TARGET_EPIPE
# define TARGET_LINUX_EPIPE 32
  [TARGET_EPIPE] = TARGET_LINUX_EPIPE,
#endif
#ifdef TARGET_EDOM
# define TARGET_LINUX_EDOM 33
  [TARGET_EDOM] = TARGET_LINUX_EDOM,
#endif
#ifdef TARGET_ERANGE
# define TARGET_LINUX_ERANGE 34
  [TARGET_ERANGE] = TARGET_LINUX_ERANGE,
#endif
#ifdef TARGET_EDEADLK
# define TARGET_LINUX_EDEADLK 35
  [TARGET_EDEADLK] = TARGET_LINUX_EDEADLK,
#endif
#ifdef TARGET_ENAMETOOLONG
# define TARGET_LINUX_ENAMETOOLONG 36
  [TARGET_ENAMETOOLONG] = TARGET_LINUX_ENAMETOOLONG,
#endif
#ifdef TARGET_ENOLCK
# define TARGET_LINUX_ENOLCK 37
  [TARGET_ENOLCK] = TARGET_LINUX_ENOLCK,
#endif
#ifdef TARGET_ENOSYS
# define TARGET_LINUX_ENOSYS 38
  [TARGET_ENOSYS] = TARGET_LINUX_ENOSYS,
#endif
#ifdef TARGET_ENOTEMPTY
# define TARGET_LINUX_ENOTEMPTY 39
  [TARGET_ENOTEMPTY] = TARGET_LINUX_ENOTEMPTY,
#endif
#ifdef TARGET_ELOOP
# define TARGET_LINUX_ELOOP 40
  [TARGET_ELOOP] = TARGET_LINUX_ELOOP,
#endif
#ifdef TARGET_ENOMSG
# define TARGET_LINUX_ENOMSG 42
  [TARGET_ENOMSG] = TARGET_LINUX_ENOMSG,
#endif
#ifdef TARGET_EIDRM
# define TARGET_LINUX_EIDRM 43
  [TARGET_EIDRM] = TARGET_LINUX_EIDRM,
#endif
#ifdef TARGET_ECHRNG
# define TARGET_LINUX_ECHRNG 44
  [TARGET_ECHRNG] = TARGET_LINUX_ECHRNG,
#endif
#ifdef TARGET_EL2NSYNC
# define TARGET_LINUX_EL2NSYNC 45
  [TARGET_EL2NSYNC] = TARGET_LINUX_EL2NSYNC,
#endif
#ifdef TARGET_EL3HLT
# define TARGET_LINUX_EL3HLT 46
  [TARGET_EL3HLT] = TARGET_LINUX_EL3HLT,
#endif
#ifdef TARGET_EL3RST
# define TARGET_LINUX_EL3RST 47
  [TARGET_EL3RST] = TARGET_LINUX_EL3RST,
#endif
#ifdef TARGET_ELNRNG
# define TARGET_LINUX_ELNRNG 48
  [TARGET_ELNRNG] = TARGET_LINUX_ELNRNG,
#endif
#ifdef TARGET_EUNATCH
# define TARGET_LINUX_EUNATCH 49
  [TARGET_EUNATCH] = TARGET_LINUX_EUNATCH,
#endif
#ifdef TARGET_ENOCSI
# define TARGET_LINUX_ENOCSI 50
  [TARGET_ENOCSI] = TARGET_LINUX_ENOCSI,
#endif
#ifdef TARGET_EL2HLT
# define TARGET_LINUX_EL2HLT 51
  [TARGET_EL2HLT] = TARGET_LINUX_EL2HLT,
#endif
#ifdef TARGET_EBADE
# define TARGET_LINUX_EBADE 52
  [TARGET_EBADE] = TARGET_LINUX_EBADE,
#endif
#ifdef TARGET_EBADR
# define TARGET_LINUX_EBADR 53
  [TARGET_EBADR] = TARGET_LINUX_EBADR,
#endif
#ifdef TARGET_EXFULL
# define TARGET_LINUX_EXFULL 54
  [TARGET_EXFULL] = TARGET_LINUX_EXFULL,
#endif
#ifdef TARGET_ENOANO
# define TARGET_LINUX_ENOANO 55
  [TARGET_ENOANO] = TARGET_LINUX_ENOANO,
#endif
#ifdef TARGET_EBADRQC
# define TARGET_LINUX_EBADRQC 56
  [TARGET_EBADRQC] = TARGET_LINUX_EBADRQC,
#endif
#ifdef TARGET_EBADSLT
# define TARGET_LINUX_EBADSLT 57
  [TARGET_EBADSLT] = TARGET_LINUX_EBADSLT,
#endif
#ifdef TARGET_EBFONT
# define TARGET_LINUX_EBFONT 59
  [TARGET_EBFONT] = TARGET_LINUX_EBFONT,
#endif
#ifdef TARGET_ENOSTR
# define TARGET_LINUX_ENOSTR 60
  [TARGET_ENOSTR] = TARGET_LINUX_ENOSTR,
#endif
#ifdef TARGET_ENODATA
# define TARGET_LINUX_ENODATA 61
  [TARGET_ENODATA] = TARGET_LINUX_ENODATA,
#endif
#ifdef TARGET_ETIME
# define TARGET_LINUX_ETIME 62
  [TARGET_ETIME] = TARGET_LINUX_ETIME,
#endif
#ifdef TARGET_ENOSR
# define TARGET_LINUX_ENOSR 63
  [TARGET_ENOSR] = TARGET_LINUX_ENOSR,
#endif
#ifdef TARGET_ENONET
# define TARGET_LINUX_ENONET 64
  [TARGET_ENONET] = TARGET_LINUX_ENONET,
#endif
#ifdef TARGET_ENOPKG
# define TARGET_LINUX_ENOPKG 65
  [TARGET_ENOPKG] = TARGET_LINUX_ENOPKG,
#endif
#ifdef TARGET_EREMOTE
# define TARGET_LINUX_EREMOTE 66
  [TARGET_EREMOTE] = TARGET_LINUX_EREMOTE,
#endif
#ifdef TARGET_ENOLINK
# define TARGET_LINUX_ENOLINK 67
  [TARGET_ENOLINK] = TARGET_LINUX_ENOLINK,
#endif
#ifdef TARGET_EADV
# define TARGET_LINUX_EADV 68
  [TARGET_EADV] = TARGET_LINUX_EADV,
#endif
#ifdef TARGET_ESRMNT
# define TARGET_LINUX_ESRMNT 69
  [TARGET_ESRMNT] = TARGET_LINUX_ESRMNT,
#endif
#ifdef TARGET_ECOMM
# define TARGET_LINUX_ECOMM 70
  [TARGET_ECOMM] = TARGET_LINUX_ECOMM,
#endif
#ifdef TARGET_EPROTO
# define TARGET_LINUX_EPROTO 71
  [TARGET_EPROTO] = TARGET_LINUX_EPROTO,
#endif
#ifdef TARGET_EMULTIHOP
# define TARGET_LINUX_EMULTIHOP 72
  [TARGET_EMULTIHOP] = TARGET_LINUX_EMULTIHOP,
#endif
#ifdef TARGET_EDOTDOT
# define TARGET_LINUX_EDOTDOT 73
  [TARGET_EDOTDOT] = TARGET_LINUX_EDOTDOT,
#endif
#ifdef TARGET_EBADMSG
# define TARGET_LINUX_EBADMSG 74
  [TARGET_EBADMSG] = TARGET_LINUX_EBADMSG,
#endif
#ifdef TARGET_EOVERFLOW
# define TARGET_LINUX_EOVERFLOW 75
  [TARGET_EOVERFLOW] = TARGET_LINUX_EOVERFLOW,
#endif
#ifdef TARGET_ENOTUNIQ
# define TARGET_LINUX_ENOTUNIQ 76
  [TARGET_ENOTUNIQ] = TARGET_LINUX_ENOTUNIQ,
#endif
#ifdef TARGET_EBADFD
# define TARGET_LINUX_EBADFD 77
  [TARGET_EBADFD] = TARGET_LINUX_EBADFD,
#endif
#ifdef TARGET_EREMCHG
# define TARGET_LINUX_EREMCHG 78
  [TARGET_EREMCHG] = TARGET_LINUX_EREMCHG,
#endif
#ifdef TARGET_ELIBACC
# define TARGET_LINUX_ELIBACC 79
  [TARGET_ELIBACC] = TARGET_LINUX_ELIBACC,
#endif
#ifdef TARGET_ELIBBAD
# define TARGET_LINUX_ELIBBAD 80
  [TARGET_ELIBBAD] = TARGET_LINUX_ELIBBAD,
#endif
#ifdef TARGET_ELIBSCN
# define TARGET_LINUX_ELIBSCN 81
  [TARGET_ELIBSCN] = TARGET_LINUX_ELIBSCN,
#endif
#ifdef TARGET_ELIBMAX
# define TARGET_LINUX_ELIBMAX 82
  [TARGET_ELIBMAX] = TARGET_LINUX_ELIBMAX,
#endif
#ifdef TARGET_ELIBEXEC
# define TARGET_LINUX_ELIBEXEC 83
  [TARGET_ELIBEXEC] = TARGET_LINUX_ELIBEXEC,
#endif
#ifdef TARGET_EILSEQ
# define TARGET_LINUX_EILSEQ 84
  [TARGET_EILSEQ] = TARGET_LINUX_EILSEQ,
#endif
#ifdef TARGET_ERESTART
# define TARGET_LINUX_ERESTART 85
  [TARGET_ERESTART] = TARGET_LINUX_ERESTART,
#endif
#ifdef TARGET_ESTRPIPE
# define TARGET_LINUX_ESTRPIPE 86
  [TARGET_ESTRPIPE] = TARGET_LINUX_ESTRPIPE,
#endif
#ifdef TARGET_EUSERS
# define TARGET_LINUX_EUSERS 87
  [TARGET_EUSERS] = TARGET_LINUX_EUSERS,
#endif
#ifdef TARGET_ENOTSOCK
# define TARGET_LINUX_ENOTSOCK 88
  [TARGET_ENOTSOCK] = TARGET_LINUX_ENOTSOCK,
#endif
#ifdef TARGET_EDESTADDRREQ
# define TARGET_LINUX_EDESTADDRREQ 89
  [TARGET_EDESTADDRREQ] = TARGET_LINUX_EDESTADDRREQ,
#endif
#ifdef TARGET_EMSGSIZE
# define TARGET_LINUX_EMSGSIZE 90
  [TARGET_EMSGSIZE] = TARGET_LINUX_EMSGSIZE,
#endif
#ifdef TARGET_EPROTOTYPE
# define TARGET_LINUX_EPROTOTYPE 91
  [TARGET_EPROTOTYPE] = TARGET_LINUX_EPROTOTYPE,
#endif
#ifdef TARGET_ENOPROTOOPT
# define TARGET_LINUX_ENOPROTOOPT 92
  [TARGET_ENOPROTOOPT] = TARGET_LINUX_ENOPROTOOPT,
#endif
#ifdef TARGET_EPROTONOSUPPORT
# define TARGET_LINUX_EPROTONOSUPPORT 93
  [TARGET_EPROTONOSUPPORT] = TARGET_LINUX_EPROTONOSUPPORT,
#endif
#ifdef TARGET_ESOCKTNOSUPPORT
# define TARGET_LINUX_ESOCKTNOSUPPORT 94
  [TARGET_ESOCKTNOSUPPORT] = TARGET_LINUX_ESOCKTNOSUPPORT,
#endif
#ifdef TARGET_EOPNOTSUPP
# define TARGET_LINUX_EOPNOTSUPP 95
  [TARGET_EOPNOTSUPP] = TARGET_LINUX_EOPNOTSUPP,
#endif
#ifdef TARGET_EPFNOSUPPORT
# define TARGET_LINUX_EPFNOSUPPORT 96
  [TARGET_EPFNOSUPPORT] = TARGET_LINUX_EPFNOSUPPORT,
#endif
#ifdef TARGET_EAFNOSUPPORT
# define TARGET_LINUX_EAFNOSUPPORT 97
  [TARGET_EAFNOSUPPORT] = TARGET_LINUX_EAFNOSUPPORT,
#endif
#ifdef TARGET_EADDRINUSE
# define TARGET_LINUX_EADDRINUSE 98
  [TARGET_EADDRINUSE] = TARGET_LINUX_EADDRINUSE,
#endif
#ifdef TARGET_EADDRNOTAVAIL
# define TARGET_LINUX_EADDRNOTAVAIL 99
  [TARGET_EADDRNOTAVAIL] = TARGET_LINUX_EADDRNOTAVAIL,
#endif
#ifdef TARGET_ENETDOWN
# define TARGET_LINUX_ENETDOWN 100
  [TARGET_ENETDOWN] = TARGET_LINUX_ENETDOWN,
#endif
#ifdef TARGET_ENETUNREACH
# define TARGET_LINUX_ENETUNREACH 101
  [TARGET_ENETUNREACH] = TARGET_LINUX_ENETUNREACH,
#endif
#ifdef TARGET_ENETRESET
# define TARGET_LINUX_ENETRESET 102
  [TARGET_ENETRESET] = TARGET_LINUX_ENETRESET,
#endif
#ifdef TARGET_ECONNABORTED
# define TARGET_LINUX_ECONNABORTED 103
  [TARGET_ECONNABORTED] = TARGET_LINUX_ECONNABORTED,
#endif
#ifdef TARGET_ECONNRESET
# define TARGET_LINUX_ECONNRESET 104
  [TARGET_ECONNRESET] = TARGET_LINUX_ECONNRESET,
#endif
#ifdef TARGET_ENOBUFS
# define TARGET_LINUX_ENOBUFS 105
  [TARGET_ENOBUFS] = TARGET_LINUX_ENOBUFS,
#endif
#ifdef TARGET_EISCONN
# define TARGET_LINUX_EISCONN 106
  [TARGET_EISCONN] = TARGET_LINUX_EISCONN,
#endif
#ifdef TARGET_ENOTCONN
# define TARGET_LINUX_ENOTCONN 107
  [TARGET_ENOTCONN] = TARGET_LINUX_ENOTCONN,
#endif
#ifdef TARGET_ESHUTDOWN
# define TARGET_LINUX_ESHUTDOWN 108
  [TARGET_ESHUTDOWN] = TARGET_LINUX_ESHUTDOWN,
#endif
#ifdef TARGET_ETOOMANYREFS
# define TARGET_LINUX_ETOOMANYREFS 109
  [TARGET_ETOOMANYREFS] = TARGET_LINUX_ETOOMANYREFS,
#endif
#ifdef TARGET_ETIMEDOUT
# define TARGET_LINUX_ETIMEDOUT 110
  [TARGET_ETIMEDOUT] = TARGET_LINUX_ETIMEDOUT,
#endif
#ifdef TARGET_ECONNREFUSED
# define TARGET_LINUX_ECONNREFUSED 111
  [TARGET_ECONNREFUSED] = TARGET_LINUX_ECONNREFUSED,
#endif
#ifdef TARGET_EHOSTDOWN
# define TARGET_LINUX_EHOSTDOWN 112
  [TARGET_EHOSTDOWN] = TARGET_LINUX_EHOSTDOWN,
#endif
#ifdef TARGET_EHOSTUNREACH
# define TARGET_LINUX_EHOSTUNREACH 113
  [TARGET_EHOSTUNREACH] = TARGET_LINUX_EHOSTUNREACH,
#endif
#ifdef TARGET_EALREADY
# define TARGET_LINUX_EALREADY 114
  [TARGET_EALREADY] = TARGET_LINUX_EALREADY,
#endif
#ifdef TARGET_EINPROGRESS
# define TARGET_LINUX_EINPROGRESS 115
  [TARGET_EINPROGRESS] = TARGET_LINUX_EINPROGRESS,
#endif
#ifdef TARGET_ESTALE
# define TARGET_LINUX_ESTALE 116
  [TARGET_ESTALE] = TARGET_LINUX_ESTALE,
#endif
#ifdef TARGET_EUCLEAN
# define TARGET_LINUX_EUCLEAN 117
  [TARGET_EUCLEAN] = TARGET_LINUX_EUCLEAN,
#endif
#ifdef TARGET_ENOTNAM
# define TARGET_LINUX_ENOTNAM 118
  [TARGET_ENOTNAM] = TARGET_LINUX_ENOTNAM,
#endif
#ifdef TARGET_ENAVAIL
# define TARGET_LINUX_ENAVAIL 119
  [TARGET_ENAVAIL] = TARGET_LINUX_ENAVAIL,
#endif
#ifdef TARGET_EISNAM
# define TARGET_LINUX_EISNAM 120
  [TARGET_EISNAM] = TARGET_LINUX_EISNAM,
#endif
#ifdef TARGET_EREMOTEIO
# define TARGET_LINUX_EREMOTEIO 121
  [TARGET_EREMOTEIO] = TARGET_LINUX_EREMOTEIO,
#endif
#ifdef TARGET_EDQUOT
# define TARGET_LINUX_EDQUOT 122
  [TARGET_EDQUOT] = TARGET_LINUX_EDQUOT,
#endif
#ifdef TARGET_ENOMEDIUM
# define TARGET_LINUX_ENOMEDIUM 123
  [TARGET_ENOMEDIUM] = TARGET_LINUX_ENOMEDIUM,
#endif
#ifdef TARGET_EMEDIUMTYPE
# define TARGET_LINUX_EMEDIUMTYPE 124
  [TARGET_EMEDIUMTYPE] = TARGET_LINUX_EMEDIUMTYPE,
#endif
#ifdef TARGET_ECANCELED
# define TARGET_LINUX_ECANCELED 125
  [TARGET_ECANCELED] = TARGET_LINUX_ECANCELED,
#endif
#ifdef TARGET_EOWNERDEAD
# define TARGET_LINUX_EOWNERDEAD 130
  [TARGET_EOWNERDEAD] = TARGET_LINUX_EOWNERDEAD,
#endif
#ifdef TARGET_ENOTRECOVERABLE
# define TARGET_LINUX_ENOTRECOVERABLE 131
  [TARGET_ENOTRECOVERABLE] = TARGET_LINUX_ENOTRECOVERABLE,
#endif
};
